### ISSUE TITLE
Token generator won't return from mfa verify post

### ISSUE THREAD

**Issue by dmakogon** [teslascope/tokens#2]
Trying to generate token, with MFA, for use with my Teslascope subscription.

Running `auth.tokens.py`, the app gets as far as the post call to `https://auth.tesla.com/oauth2/v3/authorize/mfa/verify` ([source link](https://github.com/teslascope/tokens/blob/master/auth.tokens.py#L126)). It never returns from this call.

I've now reproduced this behavior both in native Windows and in WSL2 (Ubuntu 18.04), both running Python 3.9.x. With each run, I update the passcode with the latest generated from my auth app. And I've also verified that I can still log in to the main `tesla.com` site with my credentials + mfa code.

Strangely, during one run, I was able to see an `invalid passcode` error, but have not been able to reproduce this, even when using expired passcodes.

Happy to provide more info if needed.

**Comment by corsair** [comment]
Hello there @dmakogon,

I've applied some fixes in 49fbc95 that should resolve these timeouts. Tesla adjusted the required information sent with specific requests to no longer require headers (we assume erroneously), but nonetheless, this change has been applied to any scripts that interact with their authentication system.

**Comment by dmakogon** [comment]
@corsair - just tried out the new update. Works perfectly now. Thank you!

**Comment by corsair** [comment]
@dmakogon Glad to hear! I will close this issue, but if you run into any other problems relating to this, please feel free to comment and I'll reopen this again.
