### ISSUE TITLE
No longer working for me...

### ISSUE THREAD

**Issue by insaneoctane** [teslascope/tokens#5]
I successfully used this script a little more than one month ago.  Now it's not working:

DevTools listening on ws://127.0.0.1:63948/devtools/browser/xxxx
Traceback (most recent call last):
  File "C:\xxx\tesla_tokenV3.py", line 267, in <module>
    login(args)
  File "C:\xxx\tesla_tokenV3.py", line 77, in login
    WebDriverWait(driver, 5).until(EC.presence_of_element_located((By.CSS_SELECTOR, "input[name=identity]")))
  File "C:\xxx\Python39\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

Any idea what's changed?

**Comment by jun3280net** [comment]
Running into the same problem : 
Traceback (most recent call last):
  File "auth.tokens.py", line 264, in <module>
    login(args)
  File "auth.tokens.py", line 77, in login
    WebDriverWait(driver, 5).until(EC.presence_of_element_located((By.CSS_SELECTOR, "input[name=identity]")))
  File "/home/jun3280/.local/lib/python3.6/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

Thanks

**Comment by jun3280net** [comment]
@insaneoctane - found your thread here where you solved the problem : 

[https://teslamotorsclub.com/tmc/threads/generate-v3-refresh-token-for-api-authentication-using-python.222385/](https://teslamotorsclub.com/tmc/threads/generate-v3-refresh-token-for-api-authentication-using-python.222385/)

![image](https://user-images.githubusercontent.com/30555695/116600440-8b6c3100-a8e6-11eb-9eed-d7beaec8fae4.png)

**Comment by insaneoctane** [comment]
Yes, thanks for the reminder to update here.  The issue was user agent string, see link above.
